#server:
  #port: 8080

spring:
  application:
    name: schoolWebService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8889/school_web_service?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
    #initialization-mode: always
    #schema: classpath:schema.sql

  jpa:
    hibernate:
      #create-drop #->creates db at the application launch and drops db on closing the app
      #update #->modifies tables only regarding new attributes inserted in Entities
      #validate #->for db like h2: to validate the schema of the database according to the defined entities
      #none #->default if we don't specify another one: doesn't do any changes, is used at production stage
      ddl-auto: update
      #ddl-auto: create-drop
    #generate-ddl: true
    open-in-view: false
    properties:
      #hibernate:
      dialect: org.hibernate.dialect.MYSQLDialect
    show-sql: true
  sql:
    init:
      #non #-> instructions sql in file data.sql under the file resources are not executed
      #always #->at the app launch instructions sql in file data.sql are ALWAYS executed
      mode: never


  show-sql: true


#LOGGING LEVEL
logging:
  level:
    web: debug




#CUSTOM PROPERTIES






